---
- name: Converge
  hosts: all
  become: true
  vars:
    database_password: "1234"
    database_root_password: "5678"
  tasks:
    - name: Include opencast_mariadb
      ansible.builtin.include_role:
        name: opencast_mariadb
