---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: oc_mariadb_centos_8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
lint: |
  ansible-lint
  yamllint -c .yamllint .
provisioner:
  name: ansible
  config_options:
    defaults:
      display_skipped_hosts: false
  inventory:
    host_vars:
      centos:
        ansible_user: ansible
      ubuntu:
        ansible_user: ansible
