---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: check if MariaDB is active
    command:  # noqa no-changed-when command-instead-of-module
      cmd: systemctl is-active mariadb
