---

name: molecule

on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - dist: centos
            release: 8-Stream
          - dist: centos
            release: 9-Stream
          - dist: debian
            release: buster
          - dist: debian
            release: bullseye
          - dist: ubuntu
            release: focal
          - dist: ubuntu
            release: jammy

    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: pip3 install -r .dev_requirements.txt

      - name: create lxc container
        uses: lkiesow/setup-lxc-container@v1
        with:
          dist: ${{ matrix.os.dist }}
          release: ${{ matrix.os.release }}

      - name: run molecule tests
        env:
          PY_COLORS: '1'
        run: molecule test
